"""Add authors.date_of_birth

Revision ID: 2c68bdc132be
Revises: 6dd707801380
Create Date: 2023-11-14 17:13:45.244942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c68bdc132be"
down_revision: Union[str, None] = "6dd707801380"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("name", sa.String(), nullable=False))
    op.add_column("authors", sa.Column("biography", sa.String(), nullable=True))
    op.add_column("authors", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column("categories", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "name")
    op.drop_column("authors", "date_of_birth")
    op.drop_column("authors", "biography")
    op.drop_column("authors", "name")
    # ### end Alembic commands ###
